// Universal job category taxonomy
// Covers top 40% of global employment — every major sector from tech to trades to wildlife

export interface CategoryGroup {
  group: string;
  emoji: string;
  categories: string[];
}

export const CATEGORY_GROUPS: CategoryGroup[] = [
  {
    group: "Technology & Engineering",
    emoji: "💻",
    categories: [
      "Software Engineering",
      "Product Management",
      "Data Science & Analytics",
      "Artificial Intelligence & ML",
      "Cybersecurity",
      "Cloud & Infrastructure",
      "DevOps & Site Reliability",
      "IT Support & Systems",
      "UX & Product Design",
      "QA & Testing",
      "Blockchain & Web3",
      "Developer Tools",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Chemical Engineering",
      "Civil Engineering",
      "Aerospace Engineering",
      "Biomedical Engineering",
      "Environmental Engineering",
      "Industrial Engineering",
      "Materials Science",
    ],
  },
  {
    group: "Sales & Business Development",
    emoji: "📈",
    categories: [
      "Account Executive",
      "Business Development",
      "Sales Management",
      "Sales Engineering",
      "Revenue Operations",
      "Sales Enablement",
      "Channel & Partner Sales",
      "Inside Sales",
      "Field Sales",
      "Enterprise Sales",
      "Retail Sales",
      "Real Estate Sales",
      "Pharmaceutical Sales",
      "Financial Services Sales",
      "Insurance Sales",
    ],
  },
  {
    group: "SaaS & Software Industry",
    emoji: "☁️",
    categories: [
      "CRM",
      "Sales Intelligence",
      "Revenue Intelligence",
      "Marketing Automation",
      "Customer Success Software",
      "HR Technology",
      "FinTech",
      "EdTech",
      "LegalTech",
      "HealthTech",
      "PropTech",
      "InsurTech",
      "Cybersecurity Software",
      "Data & Analytics Platform",
      "Collaboration Software",
      "Project Management Software",
      "ERP & Business Software",
      "E-Commerce Platform",
      "Gaming Technology",
    ],
  },
  {
    group: "Healthcare & Medicine",
    emoji: "🏥",
    categories: [
      "Physician & Medicine",
      "Surgery",
      "Nursing",
      "Pharmacy",
      "Physical Therapy",
      "Occupational Therapy",
      "Mental Health & Counseling",
      "Dentistry",
      "Veterinary Medicine",
      "Optometry",
      "Radiology & Imaging",
      "Emergency Medicine",
      "Pediatrics",
      "Oncology",
      "Cardiology",
      "Medical Devices",
      "Biotechnology",
      "Clinical Research",
      "Healthcare Administration",
      "Public Health",
      "Nutrition & Dietetics",
      "Speech Therapy",
      "Paramedic & EMT",
    ],
  },
  {
    group: "Education & Library Sciences",
    emoji: "📚",
    categories: [
      "K-12 Education",
      "Higher Education",
      "Special Education",
      "Early Childhood Education",
      "Corporate Training & L&D",
      "Tutoring & Coaching",
      "Library & Information Science",
      "School Administration",
      "Curriculum Development",
      "Academic Research",
      "Museum & Cultural Education",
    ],
  },
  {
    group: "Finance & Accounting",
    emoji: "💰",
    categories: [
      "Investment Banking",
      "Private Equity & Venture Capital",
      "Asset Management",
      "Financial Planning & Analysis",
      "Accounting & Audit",
      "Tax",
      "Risk & Compliance",
      "Insurance & Underwriting",
      "Mortgage & Lending",
      "Wealth Management",
      "Corporate Finance",
      "Actuarial Science",
      "Cryptocurrency & Digital Assets",
    ],
  },
  {
    group: "Legal & Government",
    emoji: "⚖️",
    categories: [
      "Corporate Law",
      "Litigation",
      "Intellectual Property",
      "Employment Law",
      "Real Estate Law",
      "Criminal Law",
      "Immigration Law",
      "Compliance & Regulatory",
      "Paralegal & Legal Support",
      "Federal Government",
      "State & Local Government",
      "Military & Defense",
      "Public Policy",
      "Intelligence & National Security",
      "Law Enforcement",
      "Fire & Emergency Services",
    ],
  },
  {
    group: "Marketing & Creative",
    emoji: "🎨",
    categories: [
      "Digital Marketing",
      "Content Marketing",
      "Brand & Communications",
      "Social Media Management",
      "SEO & SEM",
      "Performance Marketing",
      "Graphic Design",
      "Video Production & Editing",
      "Photography",
      "Copywriting & Content",
      "Public Relations",
      "Market Research",
      "Event Marketing",
      "Influencer Marketing",
      "Motion Graphics & Animation",
    ],
  },
  {
    group: "Operations & Supply Chain",
    emoji: "🏭",
    categories: [
      "Supply Chain Management",
      "Logistics & Transportation",
      "Warehouse & Distribution",
      "Manufacturing & Production",
      "Quality Assurance",
      "Procurement & Sourcing",
      "Operations Management",
      "Facilities Management",
      "Fleet Management",
      "Import & Export",
    ],
  },
  {
    group: "Human Resources & People",
    emoji: "👥",
    categories: [
      "Talent Acquisition & Recruiting",
      "HR Business Partner",
      "Compensation & Benefits",
      "HR Operations",
      "Organizational Development",
      "DEI & Culture",
      "People Analytics",
      "Executive Search",
      "Staffing & Workforce Solutions",
    ],
  },
  {
    group: "Real Estate & Construction",
    emoji: "🏗️",
    categories: [
      "Residential Real Estate",
      "Commercial Real Estate",
      "Property Management",
      "Construction Management",
      "Architecture",
      "Urban Planning",
      "Interior Design",
      "Landscape Architecture",
      "Surveying",
    ],
  },
  {
    group: "Science & Research",
    emoji: "🔬",
    categories: [
      "Biology & Life Sciences",
      "Chemistry",
      "Physics & Mathematics",
      "Environmental Science",
      "Geology & Earth Science",
      "Materials Research",
      "Space & Astronomy",
      "Neuroscience",
      "Epidemiology",
      "Social Science & Psychology",
      "Anthropology",
      "Economics & Econometrics",
    ],
  },
  {
    group: "Nature, Animals & Environment",
    emoji: "🌿",
    categories: [
      "Zoology & Zookeeping",
      "Wildlife Biology & Conservation",
      "Marine Biology & Oceanography",
      "Veterinary Science",
      "Agricultural Science",
      "Forestry & Arboriculture",
      "Horticulture & Botany",
      "Environmental Conservation",
      "Renewable Energy",
      "Sustainability",
      "Park & Recreation Management",
      "Fisheries & Aquaculture",
    ],
  },
  {
    group: "Aviation & Transportation",
    emoji: "✈️",
    categories: [
      "Airline Pilot & Aviation",
      "Air Traffic Control",
      "Aircraft Maintenance",
      "Aerospace Operations",
      "Maritime & Shipping",
      "Rail & Transit",
      "Trucking & Freight",
      "Courier & Delivery",
      "Port & Terminal Operations",
    ],
  },
  {
    group: "Hospitality, Travel & Tourism",
    emoji: "🌍",
    categories: [
      "Hotel & Resort Management",
      "Restaurant & Food Service",
      "Travel & Tour Operations",
      "Event Planning & Management",
      "Cruise & Hospitality",
      "Casino & Gaming",
      "Theme Parks & Attractions",
    ],
  },
  {
    group: "Media, Arts & Entertainment",
    emoji: "🎬",
    categories: [
      "Journalism & News",
      "Film & Television Production",
      "Music Production & Performance",
      "Gaming & Esports",
      "Book Publishing",
      "Streaming & Digital Media",
      "Sports Management & Athletics",
      "Theater & Performing Arts",
      "Fine Arts",
      "Fashion & Styling",
      "Radio & Podcasting",
    ],
  },
  {
    group: "Trades & Skilled Labor",
    emoji: "🔨",
    categories: [
      "Electrician",
      "Plumbing & HVAC",
      "Carpentry & Woodworking",
      "Automotive & Mechanics",
      "Welding & Metal Fabrication",
      "Landscaping & Grounds",
      "Cosmetology & Esthetics",
      "Culinary Arts & Chefs",
      "Masonry & Concrete",
      "Painting & Finishing",
      "Elevator & Escalator",
    ],
  },
  {
    group: "Nonprofit & Social Impact",
    emoji: "🤝",
    categories: [
      "Nonprofit Management",
      "International Development",
      "Social Work & Human Services",
      "Community Organizing",
      "Fundraising & Development",
      "Advocacy & Policy",
      "Humanitarian Aid",
      "Faith-Based Organizations",
    ],
  },
  {
    group: "Consulting & Strategy",
    emoji: "🎯",
    categories: [
      "Management Consulting",
      "Strategy & Corporate Development",
      "Business Analysis",
      "Change Management",
      "IT Consulting",
      "Financial Consulting",
      "HR Consulting",
      "Sustainability Consulting",
    ],
  },
];

export const ALL_CATEGORIES: string[] = CATEGORY_GROUPS.flatMap(g => g.categories).sort();

export function standardizeCategoryFromList(raw: string): string {
  if (!raw) return "Other";
  const lower = raw.toLowerCase().trim();
  const exact = ALL_CATEGORIES.find(c => c.toLowerCase() === lower);
  if (exact) return exact;
  const partial = ALL_CATEGORIES.find(c =>
    lower.includes(c.toLowerCase()) || c.toLowerCase().includes(lower)
  );
  return partial || raw;
}
