// Design Philosophy: "Territory Map" — Clean Professional Light Dashboard
// DM Sans (headers) + Inter (body), off-white background, deep indigo accent
// CRM-like interface with status badges, filter chips, and sortable columns

export type PipelineStage = "Research" | "Outreach" | "Applied" | "Interviewing" | "Offer" | "Rejected";

export type CompanyCategory =
  | "Sales Enablement"
  | "Revenue Intelligence"
  | "Customer Success"
  | "Marketing Automation"
  | "HR / Workforce Tech"
  | "Subscription / Billing"
  | "Social Media SaaS"
  | "Partnership Platform"
  | "EdTech SaaS"
  | "Compliance SaaS";

export interface Company {
  id: number;
  name: string;
  category: CompanyCategory;
  stage: PipelineStage;
  role: string;
  jobLink: string;
  contactName: string;
  contactTitle: string;
  contactLinkedIn: string;
  priority: "High" | "Medium" | "Low";
  notes: string;
  remoteOk: boolean;
  estSalary: string;
  companySize: string;
}

export const pipelineData: Company[] = [
  {
    id: 1,
    name: "Rippling",
    category: "HR / Workforce Tech",
    stage: "Research",
    role: "Director, Account Management, Growth + Retention",
    jobLink: "https://ats.rippling.com/rippling/jobs/e4a31a03-5370-496d-a6e1-d599a8de9e16",
    contactName: "Kevin Ori",
    contactTitle: "VP, Account Management",
    contactLinkedIn: "https://www.linkedin.com/in/kevin-ori-1b772559",
    priority: "High",
    notes: "Director-level AM role focused on growth & retention — exact match for Bryan's background. Fast-growing HCM platform.",
    remoteOk: true,
    estSalary: "$180K–$240K OTE",
    companySize: "3,000–5,000",
  },
  {
    id: 2,
    name: "Salesloft / Clari",
    category: "Revenue Intelligence",
    stage: "Research",
    role: "Enterprise Account Director",
    jobLink: "https://www.linkedin.com/jobs/view/enterprise-account-director-at-salesloft-4404124470",
    contactName: "Lee Zucker",
    contactTitle: "EVP of Sales",
    contactLinkedIn: "https://www.linkedin.com/in/leezucker",
    priority: "High",
    notes: "Revenue orchestration platform post-Clari merger. Enterprise Account Director role is a strong fit for Bryan's enterprise SaaS background.",
    remoteOk: true,
    estSalary: "$160K–$220K OTE",
    companySize: "1,000–3,000",
  },
  {
    id: 3,
    name: "Gong",
    category: "Revenue Intelligence",
    stage: "Research",
    role: "Enterprise Account Executive",
    jobLink: "https://www.linkedin.com/jobs/view/enterprise-account-executive-at-gong-4402645100",
    contactName: "Amelia Howard",
    contactTitle: "Director of Sales",
    contactLinkedIn: "https://www.linkedin.com/in/ameliahopehoward",
    priority: "High",
    notes: "Revenue AI OS platform. Strong brand, high OTE. Bryan's analytics and SaaS renewal expertise aligns well.",
    remoteOk: true,
    estSalary: "$240K–$330K OTE",
    companySize: "1,000–3,000",
  },
  {
    id: 4,
    name: "Highspot",
    category: "Sales Enablement",
    stage: "Research",
    role: "Account Director / Enterprise Sales",
    jobLink: "https://www.highspot.com/careers/",
    contactName: "Haley Katsman",
    contactTitle: "VP, Global Sales",
    contactLinkedIn: "https://www.linkedin.com/in/haleykatsman",
    priority: "High",
    notes: "Leading sales enablement platform. Bryan's experience in digital platforms and enterprise accounts is a strong match.",
    remoteOk: true,
    estSalary: "$160K–$220K OTE",
    companySize: "800–1,500",
  },
  {
    id: 5,
    name: "Seismic",
    category: "Sales Enablement",
    stage: "Research",
    role: "Enterprise Account Executive",
    jobLink: "https://www.seismic.com/careers/job-listings/",
    contactName: "James Palmer",
    contactTitle: "VP of Sales",
    contactLinkedIn: "https://www.linkedin.com/in/jamespalmervp",
    priority: "High",
    notes: "#1 global sales enablement platform. Strong enterprise focus. Bryan's background in digital content platforms is directly relevant.",
    remoteOk: true,
    estSalary: "$160K–$220K OTE",
    companySize: "1,000–2,000",
  },
  {
    id: 6,
    name: "Attentive",
    category: "Marketing Automation",
    stage: "Research",
    role: "Strategic Account Director",
    jobLink: "https://www.linkedin.com/jobs/view/strategic-account-director-at-attentive-4372109990",
    contactName: "Brian Malkerson",
    contactTitle: "Chief Revenue Officer",
    contactLinkedIn: "https://www.linkedin.com/in/brianmalkerson",
    priority: "High",
    notes: "AI-powered SMS/email marketing platform. Strategic Account Director role focused on expansion and retention — Bryan's sweet spot.",
    remoteOk: true,
    estSalary: "$180K–$250K OTE",
    companySize: "1,000–2,000",
  },
  {
    id: 7,
    name: "Klaviyo",
    category: "Marketing Automation",
    stage: "Research",
    role: "Enterprise Partner Account Manager",
    jobLink: "https://www.klaviyo.com/careers/jobs/7537750003",
    contactName: "Mike Quigley",
    contactTitle: "VP, Americas Sales",
    contactLinkedIn: "https://www.linkedin.com/in/michaelquigley",
    priority: "High",
    notes: "Leading eCommerce marketing automation platform. 193K+ customers. Bryan's SaaS AM experience is directly applicable.",
    remoteOk: true,
    estSalary: "$150K–$200K OTE",
    companySize: "2,000–4,000",
  },
  {
    id: 8,
    name: "Sprout Social",
    category: "Social Media SaaS",
    stage: "Research",
    role: "Account Executive, Enterprise",
    jobLink: "https://sproutsocial.com/careers/open-positions/7488649/",
    contactName: "Matthew Loria",
    contactTitle: "VP, Global Commercial Sales",
    contactLinkedIn: "https://www.linkedin.com/in/matthewloria",
    priority: "Medium",
    notes: "Global social media management platform. Enterprise AE role. Bryan's digital platform background is a strong fit.",
    remoteOk: true,
    estSalary: "$140K–$200K OTE",
    companySize: "800–1,500",
  },
  {
    id: 9,
    name: "Hootsuite",
    category: "Social Media SaaS",
    stage: "Research",
    role: "Senior Enterprise Account Manager",
    jobLink: "https://careers.hootsuite.com/job/?gh_jid=7710139",
    contactName: "Yannick Levieil",
    contactTitle: "Chief Sales Officer",
    contactLinkedIn: "https://www.linkedin.com/in/yannicklevieil",
    priority: "Medium",
    notes: "Social media management & analytics. Senior Enterprise AM role. Bryan's renewal and expansion expertise aligns well.",
    remoteOk: false,
    estSalary: "$130K–$180K OTE",
    companySize: "1,000–2,000",
  },
  {
    id: 10,
    name: "Gainsight",
    category: "Customer Success",
    stage: "Research",
    role: "Customer Account Manager",
    jobLink: "https://gainsight.wd5.myworkdayjobs.com/Gainsight_External_Careers",
    contactName: "Ben D.",
    contactTitle: "RVP, Enterprise Sales",
    contactLinkedIn: "https://www.linkedin.com/in/bendefoe",
    priority: "High",
    notes: "World's leading Customer Success platform. Bryan's CS-adjacent background and renewal expertise is a strong match.",
    remoteOk: true,
    estSalary: "$140K–$190K OTE",
    companySize: "800–1,500",
  },
  {
    id: 11,
    name: "Totango",
    category: "Customer Success",
    stage: "Research",
    role: "Account Manager / Customer Success",
    jobLink: "https://www.totango.com/careers",
    contactName: "Keith Frankel",
    contactTitle: "CEO",
    contactLinkedIn: "https://www.linkedin.com/in/keithfrankel",
    priority: "Medium",
    notes: "Customer-Led Growth Platform. Bryan's post-sales and renewal background is directly applicable.",
    remoteOk: true,
    estSalary: "$120K–$170K OTE",
    companySize: "200–500",
  },
  {
    id: 12,
    name: "ChurnZero",
    category: "Customer Success",
    stage: "Research",
    role: "Manager, Customer Success (Enterprise)",
    jobLink: "https://churnzero.hrmdirect.com/employment/job-opening.php?req=3626410",
    contactName: "Lukas Alexander",
    contactTitle: "VP, Customer Success",
    contactLinkedIn: "https://www.linkedin.com/in/lukasalexander",
    priority: "Medium",
    notes: "CS platform for B2B SaaS. Manager-level CS role — Bryan's 7+ years of enterprise account management is a perfect fit.",
    remoteOk: true,
    estSalary: "$130K–$180K OTE",
    companySize: "200–500",
  },
  {
    id: 13,
    name: "Zuora",
    category: "Subscription / Billing",
    stage: "Research",
    role: "Sr. Partner Account Manager",
    jobLink: "https://www.zuora.com/careers/sales-alliances/sr-partner-account-manager/",
    contactName: "Greg Masters",
    contactTitle: "SVP Sales",
    contactLinkedIn: "https://www.linkedin.com/in/greg-masters-5a19a3107",
    priority: "Medium",
    notes: "Subscription management & billing platform. Bryan's SaaS renewal and expansion expertise is highly relevant.",
    remoteOk: true,
    estSalary: "$140K–$200K OTE",
    companySize: "1,000–2,000",
  },
  {
    id: 14,
    name: "Chargebee",
    category: "Subscription / Billing",
    stage: "Research",
    role: "Account Manager / Enterprise Sales",
    jobLink: "https://www.chargebee.com/careers/",
    contactName: "Jason Mena",
    contactTitle: "Sales Leader",
    contactLinkedIn: "https://www.linkedin.com/in/jasonrmena",
    priority: "Medium",
    notes: "Billing and monetization platform for the AI economy. Bryan's SaaS background and renewal expertise is a strong fit.",
    remoteOk: true,
    estSalary: "$130K–$180K OTE",
    companySize: "500–1,000",
  },
  {
    id: 15,
    name: "Outreach",
    category: "Revenue Intelligence",
    stage: "Research",
    role: "Enterprise Account Executive",
    jobLink: "https://www.outreach.ai/careers",
    contactName: "Patrick Moran",
    contactTitle: "VP, Enterprise Sales",
    contactLinkedIn: "https://www.linkedin.com/in/patrickbmoran",
    priority: "High",
    notes: "Agentic AI platform for revenue teams. Bryan's enterprise SaaS and account management background is a direct match.",
    remoteOk: true,
    estSalary: "$180K–$260K OTE",
    companySize: "1,000–2,000",
  },
  {
    id: 16,
    name: "Zendesk",
    category: "Customer Success",
    stage: "Research",
    role: "Account Manager / Enterprise Sales",
    jobLink: "https://www.zendesk.com/company/careers/",
    contactName: "Diana Dorobek",
    contactTitle: "VP of Sales, Bay Area",
    contactLinkedIn: "https://www.linkedin.com/in/dianadorobek",
    priority: "Medium",
    notes: "AI-powered service platform. Large enterprise customer base. Bryan's SaaS AM experience is directly applicable.",
    remoteOk: true,
    estSalary: "$150K–$220K OTE",
    companySize: "5,000–10,000",
  },
  {
    id: 17,
    name: "HubSpot",
    category: "Marketing Automation",
    stage: "Research",
    role: "Account Executive / Account Manager",
    jobLink: "https://www.hubspot.com/careers/jobs/all",
    contactName: "Brian Bresee",
    contactTitle: "Senior Director of Sales, North America",
    contactLinkedIn: "https://www.linkedin.com/in/bbresee",
    priority: "Medium",
    notes: "Leading agentic customer platform. Bryan's SaaS background and enterprise account management is a strong fit.",
    remoteOk: true,
    estSalary: "$140K–$200K OTE",
    companySize: "7,000–10,000",
  },
  {
    id: 18,
    name: "Conversica",
    category: "Revenue Intelligence",
    stage: "Research",
    role: "Technical Account Manager",
    jobLink: "https://jobs.lever.co/conversica/5b4370a7-5bbf-403b-873a-540ee757fb8c",
    contactName: "Michael Gilson",
    contactTitle: "CEO",
    contactLinkedIn: "https://www.linkedin.com/in/michael-gilson-b3857918",
    priority: "Medium",
    notes: "AI-powered Digital Assistants for revenue teams. TAM role is a strong fit for Bryan's technical and customer-facing background.",
    remoteOk: true,
    estSalary: "$120K–$170K OTE",
    companySize: "100–300",
  },
  {
    id: 19,
    name: "Fingerprint",
    category: "Revenue Intelligence",
    stage: "Research",
    role: "Senior Account Manager – US",
    jobLink: "https://fingerprint.com/careers/jobs/apply/?gh_jid=5829177004",
    contactName: "Shannon Grace",
    contactTitle: "Sales Leader",
    contactLinkedIn: "https://www.linkedin.com/in/shannonagrace",
    priority: "Medium",
    notes: "Device intelligence platform for fraud detection. Senior AM role with $110K–$130K base. Bryan's SaaS AM experience is a strong fit.",
    remoteOk: true,
    estSalary: "$110K–$130K base",
    companySize: "100–300",
  },
  {
    id: 20,
    name: "SpotMe",
    category: "Marketing Automation",
    stage: "Research",
    role: "Account Director (US – Remote)",
    jobLink: "https://www.linkedin.com/jobs/view/account-director-us-remote-at-spotme-4408043048",
    contactName: "Wojciech Krawiec",
    contactTitle: "VP Product",
    contactLinkedIn: "https://www.linkedin.com/in/kraviec",
    priority: "Medium",
    notes: "Enterprise event platform for Fortune 500. Account Director role focused on multi-year enterprise contracts.",
    remoteOk: true,
    estSalary: "$130K–$180K OTE",
    companySize: "100–300",
  },
  {
    id: 21,
    name: "Ethena",
    category: "Compliance SaaS",
    stage: "Research",
    role: "Senior Enterprise Account Executive",
    jobLink: "https://www.linkedin.com/jobs/view/senior-enterprise-account-executive-at-ethena-4400621254",
    contactName: "Roxanne Bras Petraeus",
    contactTitle: "CEO",
    contactLinkedIn: "https://www.linkedin.com/in/roxanne-bras-petraeus-2292b8109",
    priority: "Medium",
    notes: "Compliance training platform with 94% positive rating. Senior AE role targeting Fortune 500. Bryan's enterprise SaaS background is a strong fit.",
    remoteOk: true,
    estSalary: "$150K–$220K OTE",
    companySize: "100–300",
  },
  {
    id: 22,
    name: "Wonderlic",
    category: "HR / Workforce Tech",
    stage: "Research",
    role: "Senior Account Manager, Growth & Expansion",
    jobLink: "https://www.linkedin.com/jobs/view/senior-account-manager-growth-expansion-at-wonderlic-4405248926",
    contactName: "Scott Sivright",
    contactTitle: "VP of Sales & Partnerships",
    contactLinkedIn: "https://www.linkedin.com/in/scottsivright",
    priority: "Medium",
    notes: "Predictive talent science platform. Senior AM role focused on growth & expansion — directly aligned with Bryan's renewal and expansion expertise.",
    remoteOk: true,
    estSalary: "$120K–$170K OTE",
    companySize: "100–300",
  },
  {
    id: 23,
    name: "Betterworks",
    category: "HR / Workforce Tech",
    stage: "Research",
    role: "Enterprise Account Executive",
    jobLink: "https://app.trinethire.com/companies/294644-betterworks-systems-inc/jobs",
    contactName: "Tyler Felber",
    contactTitle: "VP, Enterprise Sales",
    contactLinkedIn: "https://www.linkedin.com/in/tylerfelbervp",
    priority: "Medium",
    notes: "Intelligent performance management software. Enterprise AE role. Bryan's SaaS background and enterprise focus is a strong fit.",
    remoteOk: true,
    estSalary: "$140K–$200K OTE",
    companySize: "100–300",
  },
  {
    id: 24,
    name: "Allego",
    category: "Sales Enablement",
    stage: "Research",
    role: "Account Manager, Mid-Market",
    jobLink: "https://www.linkedin.com/jobs/view/account-manager-mid-market-at-allego-4410800843",
    contactName: "David Ashe",
    contactTitle: "Senior Director, Global Sales Development",
    contactLinkedIn: "https://www.linkedin.com/in/davidaashe",
    priority: "Medium",
    notes: "Sales enablement & training platform. AM role focused on customer strategy and expansion. Bryan's background is a strong fit.",
    remoteOk: false,
    estSalary: "$120K–$160K OTE",
    companySize: "200–500",
  },
  {
    id: 25,
    name: "Handshake",
    category: "HR / Workforce Tech",
    stage: "Research",
    role: "Strategic Account Manager / Enterprise Account Manager",
    jobLink: "https://joinhandshake.com/careers/",
    contactName: "Andrea Patterson",
    contactTitle: "VP, Strategic Partnerships & Growth",
    contactLinkedIn: "https://www.linkedin.com/in/handshakeandrea",
    priority: "Medium",
    notes: "Career network for the AI economy. Strategic AM role requiring 5+ years SaaS AM experience — Bryan qualifies strongly.",
    remoteOk: true,
    estSalary: "$140K–$200K OTE",
    companySize: "500–1,000",
  },
  {
    id: 26,
    name: "impact.com",
    category: "Partnership Platform",
    stage: "Research",
    role: "Creator Senior Account Manager",
    jobLink: "https://job-boards.greenhouse.io/impact/jobs/8456271002",
    contactName: "Pete Anderson",
    contactTitle: "EVP of Sales",
    contactLinkedIn: "https://www.linkedin.com/in/pete-anderson-076a3713",
    priority: "Medium",
    notes: "World's leading partnership management platform. Senior AM role in creator/affiliate space. Bryan's digital platform background is relevant.",
    remoteOk: true,
    estSalary: "$114K–$160K OTE",
    companySize: "500–1,000",
  },
  {
    id: 27,
    name: "Gainsight (CS Platform)",
    category: "Customer Success",
    stage: "Research",
    role: "Director of AI Sales",
    jobLink: "https://gainsight.wd5.myworkdayjobs.com/Gainsight_External_Careers",
    contactName: "Francisco Lozano",
    contactTitle: "Director of AI Sales",
    contactLinkedIn: "https://www.linkedin.com/in/franciscol",
    priority: "High",
    notes: "AI-powered CS platform. Director-level AI sales role — Bryan's SaaS leadership and enterprise background is a strong match.",
    remoteOk: true,
    estSalary: "$160K–$220K OTE",
    companySize: "800–1,500",
  },
  {
    id: 28,
    name: "Instructure (Canvas)",
    category: "EdTech SaaS",
    stage: "Research",
    role: "Enterprise Account Manager",
    jobLink: "https://www.instructure.com/careers",
    contactName: "Rachel Orston",
    contactTitle: "Chief Customer Officer",
    contactLinkedIn: "https://www.linkedin.com/in/rachelorston",
    priority: "Low",
    notes: "Canvas LMS — leading EdTech SaaS platform. Bryan's SaaS AM background is transferable to the EdTech vertical.",
    remoteOk: true,
    estSalary: "$120K–$170K OTE",
    companySize: "1,000–2,000",
  },
  {
    id: 29,
    name: "Panorama Education",
    category: "EdTech SaaS",
    stage: "Research",
    role: "Senior Director, Enterprise Sales",
    jobLink: "https://www.panoramaed.com/careers",
    contactName: "Jenna Persico",
    contactTitle: "Senior Director, Enterprise Sales",
    contactLinkedIn: "https://www.linkedin.com/in/jenna-persico",
    priority: "Low",
    notes: "K-12 data analytics platform. Senior Director Enterprise Sales role. Bryan's enterprise SaaS background is transferable.",
    remoteOk: true,
    estSalary: "$140K–$200K OTE",
    companySize: "200–500",
  },
  {
    id: 30,
    name: "Amplify",
    category: "EdTech SaaS",
    stage: "Research",
    role: "VP Sales / Enterprise Account Manager",
    jobLink: "https://amplify.com/careers/",
    contactName: "Trey Yost",
    contactTitle: "CRO, Panorama Education",
    contactLinkedIn: "https://www.linkedin.com/in/trey-yost",
    priority: "Low",
    notes: "K-8 literacy and math platform. VP Sales West role. Bryan's enterprise SaaS leadership background is a strong fit for the VP-level role.",
    remoteOk: true,
    estSalary: "$150K–$220K OTE",
    companySize: "500–1,000",
  },
];

export const stageColors: Record<PipelineStage, string> = {
  Research: "bg-slate-100 text-slate-700 border-slate-200",
  Outreach: "bg-amber-50 text-amber-700 border-amber-200",
  Applied: "bg-blue-50 text-blue-700 border-blue-200",
  Interviewing: "bg-violet-50 text-violet-700 border-violet-200",
  Offer: "bg-emerald-50 text-emerald-700 border-emerald-200",
  Rejected: "bg-red-50 text-red-600 border-red-200",
};

export const priorityColors: Record<"High" | "Medium" | "Low", string> = {
  High: "bg-rose-50 text-rose-700 border-rose-200",
  Medium: "bg-amber-50 text-amber-700 border-amber-200",
  Low: "bg-slate-50 text-slate-600 border-slate-200",
};

export const categoryColors: Record<CompanyCategory, string> = {
  "Sales Enablement": "bg-indigo-50 text-indigo-700",
  "Revenue Intelligence": "bg-violet-50 text-violet-700",
  "Customer Success": "bg-teal-50 text-teal-700",
  "Marketing Automation": "bg-pink-50 text-pink-700",
  "HR / Workforce Tech": "bg-orange-50 text-orange-700",
  "Subscription / Billing": "bg-cyan-50 text-cyan-700",
  "Social Media SaaS": "bg-sky-50 text-sky-700",
  "Partnership Platform": "bg-lime-50 text-lime-700",
  "EdTech SaaS": "bg-emerald-50 text-emerald-700",
  "Compliance SaaS": "bg-rose-50 text-rose-700",
};

export const stageOrder: PipelineStage[] = [
  "Research",
  "Outreach",
  "Applied",
  "Interviewing",
  "Offer",
  "Rejected",
];

export function exportToCSV(companies: Company[], filename = "bryan-pipeline.csv"): void {
  const headers = [
    "Company",
    "Category",
    "Target Role",
    "Pipeline Stage",
    "Priority",
    "Key Contact Name",
    "Contact Title",
    "Contact LinkedIn",
    "Job Posting Link",
    "Remote OK",
    "Est. Salary",
    "Company Size",
    "Notes",
  ];

  const rows = companies.map((c) => [
    c.name,
    c.category,
    c.role,
    c.stage,
    c.priority,
    c.contactName,
    c.contactTitle,
    c.contactLinkedIn,
    c.jobLink,
    c.remoteOk ? "Yes" : "No",
    c.estSalary,
    c.companySize,
    c.notes,
  ]);

  // Escape CSV values (handle commas, quotes, newlines)
  const escapedRows = rows.map((row) =>
    row
      .map((cell) => {
        const str = String(cell);
        if (str.includes(",") || str.includes('"') || str.includes("\n")) {
          return `"${str.replace(/"/g, '""')}"`;
        }
        return str;
      })
      .join(",")
  );

  const csv = [headers.join(","), ...escapedRows].join("\n");

  // Create blob and download
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  link.setAttribute("href", url);
  link.setAttribute("download", filename);
  link.style.visibility = "hidden";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
